version: "3"

services:
  notification:
    build:
      context: .
      dockerfile: ./notification_service/Dockerfile
    ports:
      - 8001:80
    networks:
      - opentracing

networks:
  opentracing:
